### PR TITLE
Download certificate

### PR DESCRIPTION
**Pull request by mdolbniak**

### CODE REVIEW

**Review by amrael — COMMENTED** [review]
Why do we need to download the file for every deployment while you could just run setup should we need to update it?

**Comment by amrael** [comment]
@mdolbniak

**Comment by mdolbniak** [comment]
@amrael I had to add new secret.json file and environment variable, I didn't know how they were downloaded/updated except this command. Btw that command downloads file only if it doesn't exist.

**Comment by amrael** [comment]
@mdolbniak The file has never been updated up until now I guess it'd be better off overwriting it manually.

**Comment by mdolbniak** [comment]
@amrael I poorly used my words, I added new, firebase_secret.json file to authenticate firebase sdk for sending notifications. I'm not overriding any existing .json files, just downloading new one. So should I put it in production containers manually instead?

**Comment by amrael** [comment]
@mdolbniak You could try running the setup recipe one by one(it may fail for some reason and ends up excluding the failed instance from the ELB, so run it carefully). And of course, you can do it manually on each web instance(web servers are not running in docker/container but on regular instances).

**Comment by mdolbniak** [comment]
@amrael Any docs on running them manually? I just need to run the downloadcertificate command, don't need to run all of them, unless there is something I don't know. And how do I set environment variable? Manually or there is some hidden configuration file?

**Comment by amrael** [comment]
@mdolbniak Which environment variable? This block, https://github.com/amrael/opsworks_django_app/blob/bf214b81ecbc1b9ed3371ecb1faadfdec9282b04/retrip/recipes/deploy.rb#L13-L25 usually takes care of it.
I guess the part you changed explains everything you need to know about running the command.

**Comment by mdolbniak** [comment]
Closing due to different authentication method

**Pull request closed without merging**
